2024-02-09 15:44:52,312 INFO    MainThread:2180 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-09 15:44:52,312 INFO    MainThread:2180 [wandb_setup.py:_flush():76] Configure stats pid to 2180
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_setup.py:_flush():76] Loading settings from /Users/mrinoyb2/.config/wandb/settings
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_setup.py:_flush():76] Loading settings from /Users/mrinoyb2/git/Wound-Detection/Notebooks/wandb/settings
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_init.py:_log_setup():526] Logging user logs to /Users/mrinoyb2/git/Wound-Detection/Notebooks/wandb/run-20240209_154452-87i1b48t/logs/debug.log
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/mrinoyb2/git/Wound-Detection/Notebooks/wandb/run-20240209_154452-87i1b48t/logs/debug-internal.log
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_init.py:init():566] calling init triggers
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-09 15:44:52,313 INFO    MainThread:2180 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 9ldazz07
2024-02-09 15:44:52,315 INFO    MainThread:2180 [wandb_run.py:_finish():1970] finishing run aipi549/wound-detection/9ldazz07
2024-02-09 15:44:52,315 ERROR   MainThread:2180 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-02-09 15:44:52,316 INFO    MainThread:2180 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-09 15:44:52,316 INFO    MainThread:2180 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-09 15:44:52,316 INFO    MainThread:2180 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-09 15:44:52,316 INFO    MainThread:2180 [wandb_run.py:_restore():2193] restore
2024-02-09 15:44:52,316 INFO    MainThread:2180 [wandb_run.py:_restore():2199] restore done
2024-02-09 15:44:56,313 INFO    MainThread:2180 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-09 15:44:56,313 INFO    MainThread:2180 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-09 15:44:56,319 INFO    MainThread:2180 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-09 15:44:57,747 INFO    MainThread:2180 [wandb_init.py:init():616] starting backend
2024-02-09 15:44:57,748 INFO    MainThread:2180 [wandb_init.py:init():620] setting up manager
2024-02-09 15:44:57,750 INFO    MainThread:2180 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-09 15:44:57,750 INFO    MainThread:2180 [wandb_init.py:init():628] backend started and connected
2024-02-09 15:44:57,760 INFO    MainThread:2180 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-09 15:44:57,760 INFO    MainThread:2180 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-09 15:44:57,760 INFO    MainThread:2180 [wandb_init.py:init():720] updated telemetry
2024-02-09 15:44:57,801 INFO    MainThread:2180 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-09 15:44:58,691 INFO    MainThread:2180 [wandb_run.py:_on_init():2262] communicating current version
2024-02-09 15:44:59,094 INFO    MainThread:2180 [wandb_run.py:_on_init():2271] got version response 
2024-02-09 15:44:59,094 INFO    MainThread:2180 [wandb_init.py:init():804] starting run threads in backend
2024-02-09 15:44:59,150 INFO    MainThread:2180 [wandb_run.py:_console_start():2241] atexit reg
2024-02-09 15:44:59,150 INFO    MainThread:2180 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-09 15:44:59,150 INFO    MainThread:2180 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-09 15:44:59,150 INFO    MainThread:2180 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-09 15:44:59,150 INFO    MainThread:2180 [wandb_init.py:init():847] run started, returning control to user process
2024-02-09 17:50:15,261 INFO    MainThread:2180 [wandb_run.py:_finish():1970] finishing run aipi549/wound-detection/87i1b48t
2024-02-09 17:50:15,261 INFO    MainThread:2180 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-09 17:50:15,262 INFO    MainThread:2180 [wandb_run.py:_restore():2193] restore
2024-02-09 17:50:15,262 INFO    MainThread:2180 [wandb_run.py:_restore():2199] restore done
2024-02-09 17:50:19,718 INFO    MainThread:2180 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-09 17:50:19,720 INFO    MainThread:2180 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-09 17:50:19,736 INFO    MainThread:2180 [wandb_run.py:_footer_sync_info():3825] logging synced files
